[font]
size = 11.0

[font.normal]
family = "MesloLGS NF"

[keyboard]
bindings = [
    { key = "Backspace", mods = "Control", chars = ""},
]

[window]
opacity = 0.8

[colors.primary]
background = '#212332'
foreground = '#d0d0d0'

[colors.cursor]
text =   '#7f85a3'
cursor = '#d0d0d0'

[colors.normal]
black =   '#444a73'
red =     '#ff5370'
green =   '#4fd6be'
yellow =  '#ffc777'
blue =    '#78A4FF'
magenta = '#fc7b7b'
cyan =    '#86e1fc'
white =   '#d0d0d0'

[colors.bright]
black =   '#828bb8'
red =     '#ff98a4'
green =   '#c3e88d'
yellow =  '#ffc777'
blue =    '#93B6FF'
magenta = '#ff966c'
cyan =    '#b4f9f8'
white =   '#5f8787'
